version: '3.8'

services:
  app:
    container_name: puppeteer-test
    build:
      context: .
      args:
        - PORT=3000
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    env_file:
      - .env
